// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Đăng nhập bằng email và mật khẩu, trả về thông tin người dùng và JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đăng nhập vào hệ thống",
                "parameters": [
                    {
                        "description": "Thông tin đăng nhập",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Đăng nhập thành công",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Dữ liệu không hợp lệ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Thông tin đăng nhập không chính xác",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Lỗi máy chủ nội bộ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Tạo một tài khoản người dùng mới với email, số điện thoại, mật khẩu và tên.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đăng ký tài khoản người dùng mới",
                "parameters": [
                    {
                        "description": "Thông tin đăng ký",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tạo tài khoản thành công",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Dữ liệu không hợp lệ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Lỗi máy chủ nội bộ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/bookings": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Người dùng đặt vé cho một chuyến đi với thông tin hành khách.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Tạo một đặt vé mới",
                "parameters": [
                    {
                        "description": "Thông tin đặt vé",
                        "name": "bookingRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Đặt vé thành công, chờ thanh toán",
                        "schema": {
                            "$ref": "#/definitions/models.Booking"
                        }
                    },
                    "400": {
                        "description": "Dữ liệu không hợp lệ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Chưa xác thực hoặc token không hợp lệ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Chuyến đi không tìm thấy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Ghế không còn trống",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Lỗi máy chủ nội bộ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/bookings/payment/mock": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Đánh dấu một đặt vé là đã thanh toán thành công (mock).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Giả lập thanh toán cho một đặt vé",
                "parameters": [
                    {
                        "description": "ID của đặt vé cần thanh toán",
                        "name": "paymentRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MockPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Thanh toán thành công, đặt vé đã được xác nhận",
                        "schema": {
                            "$ref": "#/definitions/models.Booking"
                        }
                    },
                    "400": {
                        "description": "Dữ liệu không hợp lệ hoặc đặt vé không phù hợp để thanh toán",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Chưa xác thực hoặc không có quyền",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Đặt vé không tìm thấy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Lỗi máy chủ nội bộ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/bookings/{bookingId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Người dùng lấy thông tin chi tiết của một đặt vé họ đã tạo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Lấy chi tiết một đặt vé",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID của đặt vé",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Chi tiết đặt vé",
                        "schema": {
                            "$ref": "#/definitions/models.Booking"
                        }
                    },
                    "400": {
                        "description": "ID đặt vé không hợp lệ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Chưa xác thực",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Không có quyền xem đặt vé này",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Đặt vé không tìm thấy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Lỗi máy chủ nội bộ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/trips/search": {
            "get": {
                "description": "Tìm kiếm các chuyến đi dựa trên điểm đi, điểm đến và ngày.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Tìm kiếm chuyến đi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tên điểm đi (ví dụ: Sài Gòn)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tên điểm đến (ví dụ: Đà Lạt)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ngày khởi hành (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Danh sách chuyến đi phù hợp",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Trip"
                            }
                        }
                    },
                    "400": {
                        "description": "Tham số không hợp lệ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Lỗi máy chủ nội bộ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/trips/{tripId}": {
            "get": {
                "description": "Lấy thông tin chi tiết của một chuyến đi dựa vào ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Lấy chi tiết một chuyến đi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID của chuyến đi",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Chi tiết chuyến đi",
                        "schema": {
                            "$ref": "#/definitions/models.Trip"
                        }
                    },
                    "400": {
                        "description": "ID chuyến đi không hợp lệ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Không tìm thấy chuyến đi",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Lỗi máy chủ nội bộ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Booking": {
            "type": "object",
            "properties": {
                "bookingTime": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "heldUntil": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "passengers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PassengerInfo"
                    }
                },
                "paymentGatewayTransactionId": {
                    "type": "string"
                },
                "paymentMethod": {
                    "type": "string"
                },
                "paymentStatus": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "ticketCode": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                },
                "tripId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "models.CreateBookingRequest": {
            "type": "object",
            "required": [
                "passengers",
                "tripId"
            ],
            "properties": {
                "passengers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PassengerInfo"
                    }
                },
                "tripId": {
                    "type": "string"
                }
            }
        },
        "models.GeoJSONPoint": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.MockPaymentRequest": {
            "type": "object",
            "required": [
                "bookingId"
            ],
            "properties": {
                "bookingId": {
                    "type": "string"
                }
            }
        },
        "models.PassengerInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "seatNumber": {
                    "type": "string"
                }
            }
        },
        "models.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.Route": {
            "type": "object",
            "properties": {
                "from": {
                    "$ref": "#/definitions/models.StopPoint"
                },
                "polyline": {
                    "type": "string"
                },
                "stops": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TripStop"
                    }
                },
                "to": {
                    "$ref": "#/definitions/models.StopPoint"
                }
            }
        },
        "models.StopPoint": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/models.GeoJSONPoint"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Trip": {
            "type": "object",
            "properties": {
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "departureTime": {
                    "type": "string"
                },
                "expectedArrivalTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "route": {
                    "$ref": "#/definitions/models.Route"
                },
                "seats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TripSeat"
                    }
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "vehicleId": {
                    "type": "string"
                }
            }
        },
        "models.TripSeat": {
            "type": "object",
            "properties": {
                "bookingId": {
                    "type": "string"
                },
                "seatNumber": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.TripStop": {
            "type": "object",
            "properties": {
                "expectedArrivalTime": {
                    "type": "string"
                },
                "expectedDepartureTime": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/models.GeoJSONPoint"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Bus Booking API",
	Description:      "API cho hệ thống đặt vé xe khách.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
